/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndkdemo_NativeCompress */

#ifndef _Included_com_ndkdemo_NativeCompress
#define _Included_com_ndkdemo_NativeCompress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndkdemo_NativeCompress
 * Method:    ImageCompress
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ndkdemo_NativeCompress_ImageCompress
        (JNIEnv *, jclass, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
